
// This file has been generated by the GUI designer. Do not modify.
namespace MissionControl.UI
{
	public partial class TestStandView
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget MissionControl.UI.TestStandView
			this.Name = "MissionControl.UI.TestStandView";
			this.Title = global::Mono.Unix.Catalog.GetString("TestStandView");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
