
// This file has been generated by the GUI designer. Do not modify.
namespace MissionControl.UI
{
	public partial class SVGWidget
	{
		private global::Gtk.Image imageView;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget MissionControl.UI.SVGWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "MissionControl.UI.SVGWidget";
			// Container child MissionControl.UI.SVGWidget.Gtk.Container+ContainerChild
			this.imageView = new global::Gtk.Image();
			this.imageView.Name = "imageView";
			this.Add(this.imageView);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
