
// This file has been generated by the GUI designer. Do not modify.
namespace MissionControl.UI.Widgets
{
	public partial class StateControlWidget
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget MissionControl.UI.Widgets.StateControlWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "MissionControl.UI.Widgets.StateControlWidget";
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
