
// This file has been generated by the GUI designer. Do not modify.
namespace MissionControl.UI
{
	public partial class PlotView
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget MissionControl.UI.PlotView
			this.Name = "MissionControl.UI.PlotView";
			this.Title = global::Mono.Unix.Catalog.GetString("PlotView");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
